
export const APP_URLS = {
  baseWebUrl: 'vastwebindia.com/',
  AppName: 'Smart Pay Money',
  DownloadAPK: '/Home/DownloadAPK',
  current_version: 'Common/api/data/Check_Android_Current_Version?vs_no=',
  // baseWebUrl:'http://divyanshipay.co.in/',
  DownloadAPK: '/Home/DownloadAPK',
  current_version: 'Common/api/data/Check_Android_Current_Version?vs_no=8',
  version: '5',
  AepsBankInfo: 'AEPS/api/data/AepsBankInfo',
AddharPanStatus:'api/Account/AAdharPan_Status?userid',
AadharVerificationOtpSent:'Retailer/api/data/AadharVerificationOtpSent?',
AadharVerificationOtpVerify:'Retailer/api/data/AadharVerificationOtpVerify',
PanVerification:'Retailer/api/data/PanVerification',
  purchasePanc: 'PAN/api/PAN/Pancard_Transaction_new?amount=',
  getImpsOtp: 'Money/api/Money/Imps_Send_otp?',
  Register_aadhar_new: 'Money/api/Money/Register_aadhar_new?',
  Verify_aadhar_new: 'Money/api/Money/Verify_aadhar_new?',
  PanNewRep: 'PAN/api/PAN/PANCARD_Report_new?',
  UPIQR: 'UPINEW/api/data/UPIQR',
  UPIRESPONSEPHONEPE: 'UPI/api/data/UPIRESPONSEPHONEPE?generatedid=',
  PaytmQrGenerate: 'UPINEW/api/data/Paytmqrgenerates?amount=',
  PhonePeQrGenerate: 'UPINEW/api/data/Phonepeqrgenerates?amount=',
  BharatPeQrGenerate: 'UPINEW/api/data/bharatpeqrgenerates?amount=',
  getPaytmResponse: 'UPINEW/api/data/Paytmqrresponse?txnid=',
  getPhonePeResponse: 'UPINEW/api/data/phonepeqrresponse?txnid=',
  getBharatPeResponse: 'UPINEW/api/data/bharatpeqrresponse?',
  Reset_TransPinFromRetailer: 'Retailer/api/data/Reset_TransPinFromRetailer?',
  UpdateRetailerBank: 'Retailer/api/data/UpdateRetailerBank',
  bestplanOffers: 'Recharge/api/Data/BestOfferPlan?',
  versionCheck: 'Common/api/data/BackgroundVersion',
  heavyreq: 'Recharge/api/data/DTH_Heavy_request?',
  dispute: 'Retailer/api/data/dispute?',
  forgotLoginPassword: 'api/Account/ForgotPassword',
  RtorReport: 'Retailer/api/data/rem_rem_fund_transfer_report?',
  SavedAccounts: 'Retailer/api/Data/ShowBankinfo',
  Support_Information: 'Common/api/Data/Support_Information',
  purchasePanc: 'PAN/api/PAN/Pancard_Transaction_new?amount=',
  UPIQR: 'UPINEW/api/data/UPIQR',
  PaytmQrGenerate: 'UPINEW/api/data/Paytmqrgenerates?amount=',
  PhonePeQrGenerate: 'UPINEW/api/data/Phonepeqrgenerates?amount=',
  BharatPeQrGenerate: 'UPINEW/api/data/bharatpeqrgenerates?amount=',
  getPaytmResponse: 'UPINEW/api/data/Paytmqrresponse?txnid=',
  getPhonePeResponse: 'UPINEW/api/data/phonepeqrresponse?txnid=',
  getBharatPeResponse: 'UPINEW/api/data/bharatpeqrresponse?',
  Reset_TransPinFromRetailer: 'Retailer/api/data/Reset_TransPinFromRetailer?',
  UpdateRetailerBank: 'Retailer/api/data/UpdateRetailerBank',
  bestplanOffers: 'Recharge/api/Data/BestOfferPlan?',
  versionCheck: 'Common/api/data/BackgroundVersion',
  heavyreq: 'Recharge/api/data/DTH_Heavy_request?',
  dispute: 'Retailer/api/data/dispute?',
  forgotLoginPassword: 'api/Account/ForgotPassword',
  RtorReport: 'Retailer/api/data/rem_rem_fund_transfer_report?',
  SavedAccounts: 'Retailer/api/Data/ShowBankinfo',
  Support_Information: 'Common/api/Data/Support_Information',
  signUpSvg: 'api/SVG/Login',
  planCheck: 'api/Data/PlanCheck',
  recenttransaction: 'Recharge/api/data/rem_rch_report?',
  getDistricts: 'Common/api/data/districtList?stateid=',
  getToken: 'token',
  getColors: 'Common/api/data/backgroundandfontcolor',
  getRechargeSectionImages: 'api/SVG/Rechargeandbill',
  getFinanceSectionImages: 'api/SVG/FinancialServices',
  getTravelSectionImages: 'api/SVG/TravelsandHotel',
  getOtherSectionImages: 'api/SVG/Others',
  getUserInfo: 'Common/api/inform/Get_User_Information',
  balanceInfo: 'Retailer/api/data/Show_ALL_balanceremRem',
  recharge: 'Recharge/api/data/hkhk2?',
  statelist: 'Common/api/data/statelist',
  electricity_opt_Via_StateId:
    'Recharge/api/data/Stateopearotorcodelist?Stateid=',
  viewbillstatuscheck: 'Recharge/api/data/viewbillstatuscheck?Operatorcode=',
  rechargeViewBill: 'Recharge/api/Data/viewbill?',
  getDthOperator: 'Recharge/api/data/Optcodelist?opttype=',
  getdthCustomerInfo: 'Recharge/api/Data/BestOfferPlan?',
  mobileRecCircle: 'Recharge/api/Data/Checkcircle?mobileno=',
  GetALLEduInsitutelist: 'Recharge/api/data/GetALLEduInsitutelist?',
  getStates: 'Common/api/data/statelist',
  geteduCityByStateID: 'Recharge/api/data/EducationCitybasedstate?stateids=',
  getEduStateList: 'Recharge/api/data/EducationStatelist',
  rechTask: 'Recharge/api/data/hkhk2?',
  getIndaneAgency: '/Recharge/api/data/statedis_indanegascode_api?',
  gasCylinderState: 'Recharge/api/data/StatelistBindapi',
  DistrictByState: 'Recharge/api/data/distlistbystateBindapi?statename=', //post
  hpAgency: 'Recharge/api/data/statedis_hpgascode_api?', //post
  getCheckSenderNo: 'Money/api/Money/GetBeneficiaryList?sender_number=',
  getServiceCharge: 'AEPS/api/data/ServiceCharge?Service=',
  getServicePurchase: 'AEPS/api/data/ServicePurchase?Service=',
  checkDMTStatus: 'Retailer/api/data/DMTStatusCheck',

  getServiceCharge: 'AEPS/api/data/ServiceCharge?',
  getServicePurchase: 'AEPS/api/data/ServicePurchase?Service=',
  checkDMTStatus: 'Retailer/api/data/DMTStatusCheck',
  addnewRemSendOtp: 'Money/api/Money/RegisterMobileForIMPS?',//post
  verifynewRemSendOtp: 'Money/api/Money/VerifiyOTP_ToAddNewMobile?',
  MasterIfsc: 'Money/api/Money/MasterIfsc?AccountNo=1',//get
  getGenIMPSUniqueId: 'Money/api/data/imps_Generate_Unique_ID',//get
  getBankDown: 'Money/api/Money/GetBankDown?bankname=',//get
  verifybankACC: 'Money/api/Money/mmmn2?',//post
  verifyChangePassword: '/api/Account/verifyChangePassword',
  changePassword: '/api/Account/ChangePassword',
  verifyChangePin: '/Retailer/api/data/verifychangepin?',
  changePin: '/Retailer/api/data/changepin?',
  checkSecurityType: '/Common/api/data/TwoFactorStatus',
  setTwoFAStatus: '/api/Account/TwoFactorAuthentication?',
  checkLoginPlatform: '/Common/api/data/checkuser_Loginstatus',
  plandetails: '/Retailer/api/data/PlanDetails?',
  getRechargePlans: '/Recharge/api/data/FullPlandetails?',


  getSliderImages: '/Common/api/data/appsliderimages',
  dmtapi: 'Money/api/Money/yyyy2?',
  checkUpiSdrAdhar: 'Common/api/data/',
  purchasePan: 'PAN/api/PAN/Pancard_Transaction_new?amount=',
  panCardStatusCheck: 'PAN/api/PAN/PancardStatusCheck',
  checkLivePanStatus: 'PAN/api/PAN/PSALiveCheckStatus',
  panCardInfo: 'PAN/api/PAN/PencardRegisterInformation',
  panCardRegistration: 'PAN/api/PAN/RegisterPSAPancard?',
  wallSenderList: 'WALLET/api/WALLET/GetBeneficiaryList?sender_number=',
  addwalletId: 'WALLET/api/WALLET/RegisterBeneficiary?',
  deletewalletid: "WALLET/api/WALLET/DeleteBeneficiary?",
  aepsNameinfo: 'AEPS/api/app/Aeps/AEPSNAMEFIND?mobile=',
  aadharValidation: '/Common/api/data/AdharCardValidationCheck?aadharnumber=',
  aepsBanklist: "AEPS/api/Aeps/banklist",
  adharpaysendotp: 'AEPS/api/app/Aeps/AadharpayGenrateOtp?',
  checkadharpayvideo: 'AEPS/api/app/AEPS/CheckAepsvideo?',
  uploadadharpayvideo: 'api/user/Videolink?',
  checkaepsStatus: 'AEPS/api/data/AepsStatus',
  adharpayvideostatus: 'AEPS/api/data/VideoStatus',
  sendekycotp: 'AEPS/api/data/Ekycsendotp',
  getupiList: 'UPI/api/UPI/GetBeneficiaryList?sender_number=',
  getupiList: 'UPI/api/UPI/GetBeneficiaryList?sender_number=',
  ccBanks: 'Money/api/Money/CCBankDetails',
  ccbenifeciary: "Money/api/Money/CCRemiterDetails?mobile=",
  addmoneyChg: 'Common/api/data/GetFinalChargeAmountWallet_ALL_Charges_Show?amount=',
  upicharges: 'UPI/api/data/PayBYUPICHECKSTATUS',
  upistatus: 'UPI/api/data/PayBYUPICHECKSTATUS',
  Chkpayu: 'Common/api/data/GatewayAuth?',
  sendgatewayReq: 'Common/api/data/sendgateway_request?',
  upitxChk: 'UPI/api/data/UPITRANSFERChekStatuss',
  genQr: '/UPI/api/data/UPI_Transfer?',
  chkcfSts: "UPI/api/data/cashfreestatus",
  phonepestatus: 'UPI/api/data/phonepestatus',
  phonepeurl: 'UPI/api/data/Phonepegateway?',
  upiUserDetails: "UPI/api/data/UPI_Status",
  createqr: 'UPI/api/data/ADD_UPI_Transfer?',
  impsReport: 'Money/api/Money/GetBeneIMPSReport?',
  aepsReport: 'AEPS/api/data/Retailer_Aeps_Report?',
  mposRrport: 'MPOS/api/mPos/History?',
  matmReport: 'MICROATM/api/data/MIcroAtmReport?',
  PanReport: "PAN/api/PAN/PANCARD_Report_new?",
  FlightBookReport: 'AIR/api/app/Air/TicketReport?',
  BusBookingReport: 'BUS/api/app/Bus/BusBookingReport?',
  PaymentGateway: "PaymentGateway/api/data/ShowGetewayreports?",
  posreport: 'MPOS/api/mPos/pos_ledger_report_rem?',
  WalletUnloadReport: 'WalletUnload/api/data/WalletUnloadReport?',
  finocmsReport: 'Retailer/api/data/fino_cms_report?',
  AirtelcmsReport: '',
  admindealerbankList: 'Retailer/api/data/AdminDealerBankList',
  dayErm: 'Retailer/api/data/ShowActualIncome?from=',
  dayLedger: 'Retailer/api/data/LedgerReport?',
  Addmoneyrep: '/UPI/api/data/Get_UPI_Transfer_History?',
  retailerBalRecRep: 'Retailer/api/data/BalReceive?',
  disputeReport: 'Retailer/api/data/disputelist?',
  OtherLinks: 'Common/api/data/UploadLink',
  PurchaseOrderReport: 'Retailer/api/Data/PurchaseOrderReport?',
  paytmqrgen: 'UPINEW/api/data/Paytmqrgenerates?',
  paytmresp: 'UPINEW/api/data/Paytmqrresponse?',
  opComm: 'Retailer/api/data/RetailerOpertorByCommission?',
  checkdmtstatus: 'Retailer/api/data/DMTStatusCheck',
  saveBank: 'Money/api/Money/AddNewRecipient?',
  addUpiBen: "UPI/api/UPI/RegisterBeneficiary?",
  getProfile: 'Retailer/api/v1.1/data/Rem_profile',
  updateProfile: 'Retailer/api/data/UpdateRetailerProfile',
  checkekyc: 'AEPS/api/data/CheckEkyc',
  Dmtstatus: 'Retailer/api/data/DMTStatusCheck',
  saveBank: 'Money/api/Money/AddNewRecipient?',
  cashDepositBank: 'Common/api/data/fetchCashDepositBanks',
  cashdepositGenOtp: "api/data/GenrateOtp?",
  videokycContent: 'Common/api/data/Show_Video_KYC_Content',
  twofa: 'AEPS/api/data/Validate2FA',
  AepsCheck_balance: 'AEPS/api/app/AEPS/balanceEnquiry',
  bankbenDelete: 'Money/api/Money/DeleteReceipent?',
  privacyPolicy: 'api/user/CompanyPolicyData',
  getCredoCredentials: 'MICROATM/api/data/ApiPassword',
  /////////////sign up/////////////
  joinNumCheck: 'Common/api/data/VeryFY_mailandphone?',
  joinEMverifyOtp: 'Common/api/data/VeryfyUserEmailOTP?',
  apesotpKyc: 'AEPS/api/data/EkycVerifyOtp?',
  AepsKycFinScan: 'AEPS/api/data/EkycVerifyFinger',
  AadharPay: 'AEPS/api/app/Aeps/aadharpay',
  AadharPayOtp: 'AEPS/api/app/Aeps/AadharpayGenrateOtp?',
  miniStatement: 'AEPS/api/app/AEPS/MiniStatement',
  PancardManual: 'PAN/api/PAN/PancardMenual?',
  joinNumCheck: 'Common/api/data/VeryFY_mailandphone?',
  joinEMverifyOtp: 'Common/api/data/VeryfyUserEmailOTP?',
  getMandatorySimStatus: 'Retailer/api/data/RegisterMobileStatus',
  sendMandatorySimOTP: 'Retailer/api/data/RegisterMobileStatusChange?Type=SENDOTP&OTP=""',
  verifyMandatorySimOTP: 'Retailer/api/data/RegisterMobileStatusChange?Type=VERIFYOTP&OTP=',
  getLoginPlatformStatus: 'Retailer/api/data/AppWebloginstatus',
  sendLoginPlatformOtp: 'Retailer/api/data/UpdateAppWebloginstatus?LoginType={TYPE}&Type=SENDOTP&OTP=""',
  verifyUpdateLoginPlatformOtp: 'Retailer/api/data/UpdateAppWebloginstatus?LoginType={TYPE}&Type=VERIFYOTP&OTP=',
  getRegistrationDevices: 'Retailer/api/data/AppLoginDevicewise',
  registerDevice: 'Retailer/api/data/RegisterImei?imeino={uniqueId}&Type=SENDOTP&OTP={otp}&commandtype=',
  registerDeviceVerifyOTP: 'Retailer/api/data/RegisterImei?imeino={uniqueId}&Type=VERIFYOTP&OTP={otp}&commandtype=',
  HoldAndCreditReport: '/MICROATM/api/data/Micro_Atm_hold_Rem_Report',
  NewsNotifaction: '/Retailer/api/data/AppNotifications',
  getCashPickupTransactionList: 'api/RadiantCash/CashPickUpList',
  getMasterRemarkList: 'api/RadiantCash/MasterRemarkList',
  getChildRemarkList: 'api/RadiantCash/ChildRemarkList?masterRemark=',
  sendRadiantOtp: 'api/RadiantCash/OtpProcess',
  setDynamicOtp: 'api/RadiantCash/DynamicOtpProcess',
  submitCashPickup: 'api/RadiantCash/CashpickupSubmit',
  radiantQRCashPickup: 'api/RadiantCash/QRCashpickupSubmit',

};



// /Common/api/data/TwoFactorStatus  {  no params}
// /api/Account/TwoFactorAuthentication?status=status&passcodetype=passcodetype   // (ex-status=true$passcodetype=OTP  || status=false$passcodetype=OFF   ||  )
// /Common/api/data/checkuser_Loginstatus  {np params}
// /Retailer/api/data/changepin?OldPIN=OldPIN&NewPIN=NewPIN
// /api/data/Transectionpinchange?oldpin=oldpin&newpin=newpin
// /api/Account/ChangePassword?OldPassword="OldPassword"&NewPassword="NewPassword"&ConfirmPassword="ConfirmPassword"
// /Retailer/api/data/Reset_TransPinFromRetailer  {txtemail:'mailid'}