export const stateData = [
  {stateId: 1, stateName: 'Andaman and Nicobar Islands'},
  {stateId: 2, stateName: 'Andhra Pradesh'},
  {stateId: 3, stateName: 'Arunachal Pradesh'},
  {stateId: 4, stateName: 'Assam'},
  {stateId: 5, stateName: 'Bihar'},
  {stateId: 6, stateName: 'Chandigarh'},
  {stateId: 7, stateName: 'Chhattisgarh'},
  {stateId: 8, stateName: 'Dadar Nagar Haveli'},
  {stateId: 9, stateName: 'Daman and Diu'},
  {stateId: 10, stateName: 'Delhi'},
  {stateId: 11, stateName: 'Goa'},
  {stateId: 12, stateName: 'Gujarat'},
  {stateId: 13, stateName: 'Haryana'},
  {stateId: 14, stateName: 'Himachal Pradesh'},
  {stateId: 15, stateName: 'Jammu and Kashmir'},
  {stateId: 16, stateName: 'Jharkhand'},
  {stateId: 17, stateName: 'Karnataka'},
  {stateId: 18, stateName: 'Kerala'},
  {stateId: 19, stateName: 'Lakshadweep'},
  {stateId: 20, stateName: 'Madhya Pradesh'},
  {stateId: 21, stateName: 'Maharashtra'},
  {stateId: 22, stateName: 'Manipur'},
  {stateId: 23, stateName: 'Meghalaya'},
  {stateId: 24, stateName: 'Mizoram'},
  {stateId: 25, stateName: 'Nagaland'},
  {stateId: 26, stateName: 'Orissa'},
  {stateId: 27, stateName: 'Pondicherry'},
  {stateId: 28, stateName: 'Punjab'},
  {stateId: 29, stateName: 'Rajasthan'},
  {stateId: 30, stateName: 'Sikkim'},
  {stateId: 31, stateName: 'Tamil Nadu'},
  {stateId: 32, stateName: 'Tripura'},
  {stateId: 33, stateName: 'Uttar Pradesh'},
  {stateId: 34, stateName: 'Uttarakhand'},
  {stateId: 35, stateName: 'West Bengal'},
];
